**Encoding**

* encoding refers to changing categorical data into numerical data
* types of encoding :- 1. ordinal encoding 2. label encoding 3. onehot encoding

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('laptop_data.csv')
data

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [3]:
x = data[['Company']]
y = data[['TypeName']]
x_train , x_test, y_train, y_test = train_test_split(x , y ,test_size = 0.33 , random_state=2)

* 1. Ordinal Encoding

In [4]:
from sklearn.preprocessing import OrdinalEncoder
en = OrdinalEncoder()
encode = en.fit_transform(x_train)
pd.DataFrame(encode, columns=['Company'])

     Company
0        4.0
1        7.0
2       10.0
3        4.0
4        7.0
..       ...
868      0.0
869      2.0
870      0.0
871      9.0
872      7.0

[873 rows x 1 columns]

In [5]:
from sklearn.preprocessing import OrdinalEncoder
en = OrdinalEncoder()
encode = en.fit_transform(x_train)

* 2. Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
en = LabelEncoder()
encode = en.fit_transform(x_train)
pd.DataFrame(encode, columns=['TypeName'])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

     TypeName
0           4
1           7
2          10
3           4
4           7
..        ...
868         0
869         2
870         0
871         9
872         7

[873 rows x 1 columns]

* 3. Onehot Encoding

In [7]:
from sklearn.preprocessing import OneHotEncoder
en1 = OneHotEncoder()
encode = en1.fit_transform(x_train)
pd.DataFrame(encode, columns=['TypeName'])

           TypeName
0       (0, 4)\t1.0
1       (0, 7)\t1.0
2      (0, 10)\t1.0
3       (0, 4)\t1.0
4       (0, 7)\t1.0
..              ...
868     (0, 0)\t1.0
869     (0, 2)\t1.0
870     (0, 0)\t1.0
871     (0, 9)\t1.0
872     (0, 7)\t1.0

[873 rows x 1 columns]